version: "3.8"

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: e-commerce-store-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommercestore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
    ports:
      - "5432:5432"
    volumes:
      - ecommerce_data:/var/lib/postgresql/data
      # Initialize database with schema and seed data
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommercestore

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: e-commerce-store-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=database
      - POSTGRES_DB=ecommercestore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newpassword
      - POSTGRES_PORT=5432
      - PORT=9000
      - SECRET=your-jwt-secret-key
      - REFRESH_SECRET=your-refresh-secret-key
    ports:
      - "9000:9000"
    depends_on:
      - database
    networks:
      - ecommercestore
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: e-commerce-store-client
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:9000
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - ecommercestore
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

networks:
  ecommercestore:
    driver: bridge

volumes:
  ecommerce_data:
    driver: local
