# Global configuration
global:
  scrape_interval: 15s      
  evaluation_interval: 15s 
  external_labels:
    monitor: 'pern-store-monitor'
    environment: 'production'

# Scrape configurations
scrape_configs:
  # Job 1: Prometheus itself (self-monitoring)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job 2: Node Exporter (System metrics - CPU, RAM, Disk, Network)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ec2-instance'

  # Job 3: cAdvisor (Docker container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'docker-containers'

  # Job 4: PERN App Backend (Application metrics)
  - job_name: 'pern-backend'
    static_configs:
      - targets: ['pern-server:9000']  
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'pern-app'
